#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source
git clone https://github.com/yshui/picom || true

# update source
cd picom
git pull

# compile
git submodule update --init --recursive
meson --buildtype=release . build || meson --reconfigure
ninja -C build

# install
sudo ln -sf $(pwd)/build/src/picom /bin
