#!/usr/bin/env bash

cd git_src  

#compile
git submodule update --init --recursive
meson --buildtype=release . build || meson --reconfigure
ninja -C build

# install
sudo ln -sf $(pwd)/build/src/picom /bin
