#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source
[ -f FiraCode.zip ] || wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
[ -f SourceCodePro.zip ] || wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/SourceCodePro.zip

unzip SourceCodePro.zip
unzip FiraCode.zip

mkdir -p $HOME/.local/share/fonts
mv *.ttf *.otf $HOME/.local/share/fonts
