#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source
[ -f FiraCode.zip ] || wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
[ -f SourceCodePro.zip ] || wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/SourceCodePro.zip

unzip -o SourceCodePro.zip -d .
unzip -o FiraCode.zip -d .

mkdir -p $HOME/.local/share/fonts
mv *.ttf $HOME/.local/share/fonts
fc-cache
