#!/usr/bin/env bash

if [[ ${DEBUG-} =~ ^1|yes|true$ ]]; then
    set -o xtrace       # Trace the execution of the script (debug)
fi

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o errtrace     # Ensure the error trap handler is inherited

# while ! [ -d "$HOME/.ssh" ] ; do
#   echo "No SSH key created, let's create one..."
#   printf "Mail: "
#   read mail
#   ssh-keygen -t ed25519 -C "$mail"
#   eval "$(ssh-agent -s)"
#   ssh-add ~/.ssh/id_ed25519
# done

while ! ssh -T git@github.com 2>&1 | grep "successfully" > /dev/null ; do 
  echo
  echo "Log into your accont with SSH:"
  echo
  gh auth login
  # printf "SSH key title: "
  # read ssh_key_title
  # gh ssh-key add ~/.ssh/id_ed25519 -t "$ssh_key_title"
done

if ! [ -d $HOME/.gnupg ] ; then
  gpg --full-generate-key
fi

if ! [ -d $HOME/.password-store ] ; then
  printf "Mail for password store: " 
  read mail
  pass init $mail 
fi

while ! [ -f $HOME/.password-store/nay.gpg ] ; do 
  nay setpass
done

export GPG_TTY=$(tty)

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
case "$distro_name" in
  Arch)
    yay -Syu
    nay init git@github.com:Federico-Ciuffardi/nay-arch.git
    nay pull_force --yes nay-arch
    nay init git@github.com:Federico-Ciuffardi/nay-dotfiles.git
    nay pull_force --yes nay-dotfiles
    ;;
  Ubuntu)
    nay init git@github.com:Federico-Ciuffardi/nay-dotfiles-ubuntu.git
    nay init git@github.com:Federico-Ciuffardi/nay-ubuntu.git
    ;;
  *)
    echo "Unsuported distro \"$distro_name\""
    ;;
esac

# Enable services
sudo systemctl --now enable NetworkManager.service 
sudo systemctl --now enable acpid.service
sudo systemctl --now enable ntpd.service

# change shell
sudo usermod --shell /bin/zsh fede 

echo "Success!"

