#!/usr/bin/env bash

if [[ ${DEBUG-} =~ ^1|yes|true$ ]]; then
    set -o xtrace       # Trace the execution of the script (debug)
fi

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o errtrace     # Ensure the error trap handler is inherited

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
case "$distro_name" in
  Arch)
    nay init git@github.com:Federico-Ciuffardi/nay-arch.git
    nay pull_force --yes nay-arch
    nay init git@github.com:Federico-Ciuffardi/nay-dotfiles.git
    nay pull_force --yes nay-dotfiles
    ;;
  Ubuntu)
    nay init git@github.com:Federico-Ciuffardi/nay-dotfiles-ubuntu.git
    nay init git@github.com:Federico-Ciuffardi/nay-ubuntu.git
    ;;
  *)
    echo "Unsuported distro \"$distro_name\""
    ;;
esac

