#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

git clone https://github.com/ra-c/libxft-bgra-debian || true
cd libxft-bgra-debian
git pull
cd compiled
sudo dpkg -i *.deb
sudo apt --fix-broken install -y
sudo dpkg -i *.deb
sudo apt --fix-broken install -y
sudo dpkg -i *.deb
