#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source 
git clone https://github.com/natsukagami/mpd-mpris || true
cd mpd-mpris

# update source
git pull

# compile and install
go build -v -o mpd-mpris cmd/mpd-mpris/*.go
sudo ln -sf $(pwd)/mpd-mpris /bin/mpd-mpris
