#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source 
git clone https://github.com/Federico-Ciuffardi/st.git || true
cd st

# update source
git pull

# compile and install
sudo make install
