#!/usr/bin/env bash

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
if [ "$distro_name" != "Arch" ] ; then
  echo "Package only for Arch"
  exit 1
fi

cd git_src 
makepkg --noconfirm
sudo pacman -U --noconfirm *.pkg.tar.zst
git clean -fdx # clean packages after install to prevent potential conflicts
