#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

#!/bin/sh
# sudo mkdir -p /etc/hosts.d
# wget -O 99blocklist.conf https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# sudo cp 99blocklist.conf /etc/hosts.d/

# git clone https://github.com/Ewpratten/youtube_ad_blocklist || true
# cd youtube_ad_blocklist
# python3 generator.py
# sudo cp output/hosts.ipv4.txt /etc/hosts.d/98youtube-blocklist.conf

# # Now download the new hosts file and put it into place
# wget -O 97ultimate_ad_blocklist.conf https://hosts.ubuntu101.co.za/hosts
# sudo cp 97ultimate_ad_blocklist.conf /etc/hosts.d/

# sudo cp /etc/hosts /etc/hosts.bak
# cat /etc/hosts.d/*.conf | sudo tee /etc/hosts
