#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

wget -O vieb.deb https://github.com/Jelmerro/Vieb/releases/download/5.3.0/vieb_5.3.0_amd64.deb
sudo dpkg -i *.deb
sudo apt --fix-broken install -y
