#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source
git clone git@github.com:mwh/dragon.git || true

# update source
cd dragon 
git pull

# compile
make

# install
sudo ln -sf $(pwd)/dragon /bin/dragon-drag-and-drop
