#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

# get source 
git clone https://github.com/neovim/neovim || true
cd neovim

# update source
git pull

# compile and install
make CMAKE_BUILD_TYPE=Release
sudo make install
