#!/usr/bin/env bash

set -o errexit      # Exit on most errors (see the manual)
set -o nounset      # Disallow expansion of unset variables
set -o pipefail     # Use last non-zero exit code in a pipeline
set -o errtrace     # Ensure the error trap handler is inherited

dpkg -s "isync" &>/dev/null || sudo apt install -y isync
dpkg -s "msmtp" &>/dev/null || sudo apt install -y msmtp
dpkg -s "curl" &>/dev/null || sudo apt install -y culr 
dpkg -s "pass" &>/dev/null || sudo apt install -y pass
